- name: 'Atualiza apt se necessário'
  apt:
    upgrade: 'yes'
    update_cache: yes
    cache_valid_time: 86400 #Um dia
  become: 'yes'

- name: 'Instala pacotes de dependências do sistema operacional'
  apt:
    name: [ 
      'php7.2',
      'apache2',
      'libapache2-mod-php7.2',
      'php7.2-gd',
      'libssh2-1',
      'php-ssh2', 
      'mysql-client-5.7',
      'python3.7',
      'python3-pip',
      'php7.2-mysql'
    ]
    state: latest
  become: 'yes'

- name: 'Baixa o arquivo de instalação do Wordpress'
  get_url:
    url: 'https://wordpress.org/latest.tar.gz'
    dest: '/tmp/wordpress.tar.gz'

- name: 'Descompacta o Wordpress'
  unarchive:
    src: '/tmp/wordpress.tar.gz'
    dest: '/var/www/'
    remote_src: 'yes'
  become: 'yes'

- name: 'Configura Wordpress'
  copy:
    src: "{{ wp_installation_dir }}/wp-config-sample.php"
    dest: "{{ wp_installation_dir }}/wp-config.php"
    remote_src: 'yes'
  become: 'yes'

- name: 'Configura o wp-config para utilizar o banco de dados'
  replace:
    path: "{{ wp_installation_dir }}/wp-config.php"
    regexp: "{{ item.regex }}"
    replace: "{{ item.value }}"
    backup: 'yes'
  with_items:
    - { regex: 'database_name_here', value: "{{ wp_db }}" }
    - { regex: 'username_here', value: "{{ wp_username }}" }
    - { regex: 'password_here', value: "{{ wp_password }}" }
    - { regex: 'localhost', value: "{{ wp_db_ip }}" }
  become: 'yes'

- name: 'Configura o Apache para servir o Wordpress'
  template:
    src: 'templates/000-default.conf.j2'
    dest: '/etc/apache2/sites-available/000-default.conf'
  become: 'yes'
  notify: 
    - restart apache