- name: 'Atualiza apt se necessário'
  apt:
    upgrade: 'yes'
    update_cache: yes
    cache_valid_time: 86400 #Um dia
  become: 'yes'

- name: 'Instala pacotes de dependências do sistema operacional'
  apt:
    name: [ 
      'mysql-server-5.7', 
      'python3.7',
      'python3-pip',
      'python3-mysqldb'
    ]
    state: latest
  become: 'yes'

- name: 'Garante instalação dos modulos do Python'
  pip: 
    name: 'pymysql'
    state: present
  become: 'yes'

- name: 'Reinicia o MySQL'
  service:
    name: mysql
    state: restarted
  become: 'yes'

- name: 'Configura MySQL para aceitar conexões remotas'
  copy:
    src: files/mysqld.cnf
    dest: /etc/mysql/mysql.conf.d/mysqld.cnf
    owner: root
    group: root
    mode: 0644
  become: 'yes'
  notify:
    - restart mysql

- name: 'Configura usuário do mysql'
  shell: mysql -e "CREATE USER '{{ wp_username }}'@'%' IDENTIFIED BY '{{ wp_password }}';"
  ignore_errors: 'yes'
  become: 'yes'

- name: 'Adiciona permissão de usuário do mysql'
  shell: mysql -e "GRANT ALL PRIVILEGES ON *.* TO '{{ wp_username }}'@'%';"
  ignore_errors: 'yes'
  become: 'yes'

- name: 'Cria banco de dados MySQL'
  mysql_db: 
    name: "{{ wp_db }}"
    login_user: "{{ wp_username }}"
    login_password: "{{ wp_password }}" 
    state: present
  become: 'yes'